name: Test SBT Project
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/gitHubActionsAssignmentThree
  pull_request:
    branches:
      - master
      - feature/gitHubActionsAssignmentThree
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
         ref: feature/gitHubActionsAssignmentThree

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Run sbt command
      run: |
           cd SBT_Project/
           sbt clean compile
