name: GitHub Actions Assignment Two

on:
  push:
    branches:
      - feature/gitHubActionsAssignmentTwo
  workflow_dispatch:

jobs:
  postman-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '16'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Collection
        run: newman run Postman_Collection/GitHub_Action_Assignment_1.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export test_report.html

      - name: Archive Postman report
        uses: actions/upload-artifact@v2
        with:
          name: Postman Report
          path: test_report.html
          retention-days: 30

  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and run Selenium tests
        run: |
             cd Selenium_Project/Broken_Link
             mvn clean test

      - name: Archive Selenium test report
        uses: actions/upload-artifact@v2
        with:
          name: Selenium Test Report
          path: Selenium_Project/Broken_Link/target/surefire-reports
          retention-days: 30
