name: Test Postman Collection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '16'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Collection
        run: newman run Postman_Collection/GitHub_Action_Assignment_1.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export test-report.html

      - name: Archive Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.html
          retention-days: 30
